import { chromium } from "playwright"
const POS = "http://localhost:8081", CLAVE = "Sigh#Test2026"
const b = await chromium.launch({ channel: "chrome", headless: true })
const ctx = await b.newContext({ viewport: { width: 1280, height: 800 }, locale: "es-MX" })
const page = await ctx.newPage()
page.on("dialog", (d) => d.accept().catch(() => {}))
await page.goto(`${POS}/login`, { waitUntil: "commit" })
await page.locator("input").first().waitFor({ timeout: 60000 })
await page.waitForTimeout(1200)
await page.locator("input").nth(0).fill("enfermeria")
await page.locator("input").nth(1).fill(CLAVE)
await page.getByText("Entrar", { exact: true }).first().click({ force: true })
await page.waitForTimeout(7000)
const orden = page.locator('[aria-label^="Orden de María"]').first()
console.log("ordenes de María:", await orden.count())
await orden.click({ force: true })
await page.waitForTimeout(3000)
const aplicar = page.getByText(/^Aplicar \(/)
console.log("botones Aplicar(n):", await aplicar.count(), await aplicar.first().innerText().catch(() => "?"))
await aplicar.first().click({ force: true })
await page.waitForTimeout(2500)
const cuerpo = await page.locator("body").innerText()
console.log("¿diálogo?:", /¿Aplicar esta orden\?/.test(cuerpo))
const exactos = page.getByText("Aplicar", { exact: true })
console.log("Aplicar exacto:", await exactos.count(), "visibles:", await exactos.filter({ visible: true }).count())
console.log(cuerpo.split("\n").filter((l) => /Aplicar|Revisar|orden/i.test(l)).slice(0, 12).join(" | "))
await page.screenshot({ path: process.env.TMP + "/dbg-aplicar.png" })
await b.close()
